MOM6-cases/ocean_only/ISOMIP/sigma_zstar/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/sigma_zstar/01.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/sigma_zstar/12.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/sigma_zstar/02.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/sigma_zstar/ocean.stats.%: ALT_NPES=32
MOM6-cases/ocean_only/ISOMIP/layer/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/layer/01.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/layer/12.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/layer/02.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/ISOMIP/layer/ocean.stats.%: ALT_NPES=32
MOM6-cases/ocean_only/double_gyre/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/double_gyre/01.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/double_gyre/12.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/double_gyre/02.ignore/ocean.stats.%: NPES=36
MOM6-cases/ocean_only/double_gyre/ocean.stats.%: ALT_NPES=32
MOM6-cases/ocean_only/double_gyre/ocean.stats.%: STATIC_NPES=8
STATIC_OCEAN_ONLY = DOME nonBous_global benchmark double_gyre
